version: '3'

services: 
  producer:
    build: .
    container_name: producerComment
    restart: always
    volumes:
      - ./productor&consumidor:/app
    command: >
      sh -c "python3 /app/productorComment.py"
  consumer:   
    build: .
    container_name: consumerComment
    restart: always
    volumes: 
        - ./productor&consumidor:/app
    command: >
        sh -c "python3 /app/consumerComment.py"
networks: 
  default:
    external: 
      name: app