version: '3'

services:
  producer:
    build: .
    container_name: producerStatistics
    restart: always
    volumes:
      - ./productor&consumidor:/app
    command: >
      sh -c "python3 /app/productorStatistics.py"
networks: 
  default:
    external: 
      name: app
